# Generated by Django 5.1.2 on 2024-10-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employeemodel_emp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
