# Generated by Django 5.1.2 on 2024-10-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employeemodel_emp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='emp_email',
        ),
    ]
